### ISSUE TITLE
Kretes CLI commands passes if user types invalid command

### ISSUE THREAD

**Issue by michaelKurowski** [kreteshq/kretes#106]
Kretes v.0.70.0, CLI
OS: Windows 10 (WSL2)

 CLI command passes silently if the user mistypes the command - it throws no output at all, just passes.

**Comment by zaiste** [comment]
@michaelKurowski this is fixed in https://github.com/kreteshq/kretes/commit/c5178dcf680364de8ee53ed3b804baeccbe50349 

I haven't tested the tool extensively on Win. There may be issues :) I'm working on it. Feel free if you stumble on something.
