### ISSUE TITLE
kretes_1.database is not a function

### ISSUE THREAD

**Issue by michaelKurowski** [kreteshq/kretes#108]
Kretes: 0.71
OS: Ubuntu 18.04.4 LTS

Using database as in [documentation](https://kretes.dev/docs/guide/in-depth/database/), throws an error:
![image](https://user-images.githubusercontent.com/2772942/96267627-52aedf00-0fc8-11eb-84d5-a04b98827bd6.png)

As `database` exported member from kretes is not recognized as a function, so passing template literals to it doesn't work.

**Comment by zaiste** [comment]
@michaelKurowski could you run `pgcli` as shown in this video and show me your results when executing the `\d` command ?

![2020-10-16 18 23 07](https://user-images.githubusercontent.com/200613/96284154-7cbecc00-0fdd-11eb-94fe-2157a6e16028.gif)

**Comment by michaelKurowski** [comment]
```
mkurowski@mkurowski-Latitude-5480:~/OSS/kretes-example-app/kretes_demo$ nix-shell --run 'sh'
sh-4.4$ pgcli
Server: PostgreSQL 12.4
Version: 3.0.0
Chat: https://gitter.im/dbcli/pgcli
Home: http://pgcli.com
postgres> \d
+----------+--------+--------+---------+
| Schema   | Name   | Type   | Owner   |
|----------+--------+--------+---------|
+----------+--------+--------+---------+
SELECT 0
Time: 0.037s
postgres>

```

**Comment by zaiste** [comment]
@michaelKurowski in `pgcli` could you run

```
create table widgets (
  id serial primary key,
  name text,
  amount integer
);
```

and then try to trigger the `browse` route again ?

**Comment by zaiste** [comment]
@michaelKurowski I've updated [the docs](https://kretes.dev/docs/guide/in-depth/database/). Feel free to reopen if the error doesn't go away on your side.
