### ISSUE TITLE
Property 'returning' does not exist on type SQW

### ISSUE THREAD

**Issue by daksamit** [kreteshq/kretes#109]
Kretes: 0.71
OS: Ubuntu 20.04 LTS

According to [documentation](https://kretes.dev/docs/guide/in-depth/database/)
example with returning function underlines eslint rule: "Property 'returning' does not exist on type SQW"
![image](https://user-images.githubusercontent.com/7165997/96268401-51ca7d00-0fc9-11eb-9eb7-6ab424a566b4.png)

It seems to be related to #108

**Comment by zaiste** [comment]
@daksamit Just to confirm, is the query executing correctly ? Sometimes I've seen errors in VS Code, with code running OK. Is the VS Code correctly picking up TypeScript `4.x` ?

**Comment by daksamit** [comment]
No, unfortunately, I have the same problem as described here #108

**Comment by zaiste** [comment]
@daksamit I've updated [the docs](https://kretes.dev/docs/guide/in-depth/database/) for that part. The previous version of docs *assumed* that the database tables are created by the user. `widgets` was just a placeholder to show the general idea. I've improved that. Let me know if it solves that.
