### ISSUE TITLE
Documentation on Requirements

### ISSUE THREAD

**Issue by seangates** [kreteshq/kretes#38]
Currently, I'm getting an error when attempting to use the CLI to create a new project.

Specifically, what are the requirements for my environment? What version of Node? What version of NPM?

Please update the README with this information so I can quickly understand what to install before I use `huncwot`.

**Comment by seangates** [comment]
I see node 7.6+, but is there anything else?

**Comment by zaiste** [comment]
The docs are now available at https://kretes.dev
