### ISSUE TITLE
Seeding the database?

### ISSUE THREAD

**Issue by emilos** [kreteshq/kretes#76]
Have you considered having a convention for seeding the database? Something like `npm run db:seed` would be pretty useful. It could iterate over files in some directory (or one file only for simplicity), clear the db and seed it with new data.

**Comment by zaiste** [comment]
@emilos Yes! Ideally, I'd like to store the seed data as plain SQL (`insert`s, `update`s, etc), but at the same I'd like there is a sort of visual UI build on top of VS Code so that you could set this data conveniently without bothering about the SQL syntax. What do you think ?

**Comment by emilos** [comment]
The approach makes sense, I guess it's good enough for simple data.

For more complex scenarios it would be nice to allow importing models and seed the db by using them. This way you can easily have fake data, loops and other utilities which are not that easy in plain sql.

**Comment by zaiste** [comment]
The database CLI has been added: https://kretes.dev/docs/guide/in-depth/cli/#commands
