### ISSUE TITLE
Error: exit code 1 

### ISSUE THREAD

**Issue by 3rly** [kreteshq/kretes#97]
I don't know if this error is a result of the many deprecated files that Kretes currently imports, but I cannot find any way around fixing this bug. Please review and advise. Thank you for your assistance.

![image](https://user-images.githubusercontent.com/55966724/86707511-083fbe80-bfe6-11ea-892c-d48052e45970.png)

**Comment by zaiste** [comment]
@3rly Sorry for the trouble. I'm trying to test it in different scenarios, but some edge cases evade me. I'm looking into it.

**Comment by zaiste** [comment]
@3rly just to be sure, could you confirm you have (1) run `npm install` in the project directory, or (2) used `Kretes: Install` if in VS Code), or (3) used `kretes new` without the `--no-npm-install` flag before starting the app ?

**Comment by 3rly** [comment]
@zaiste I attempted all (3) of the scenarios in my attempts to debug and get it running, except the last one. Therefore. let me attempt the last suggestion and I will let you know. Thank you for your assistance.

**Comment by marcociciriello** [comment]
@zaiste I'm currently experiencing the same issue - I've performed each of the three steps mentioned in your previous comment (including from a fresh npm install) and the issue is persisting. 
![image](https://user-images.githubusercontent.com/40694097/87822846-20c39a80-c86a-11ea-8369-8512184026e5.png)

**Comment by 3rly** [comment]
@zaiste To follow up on this issue. My resolution might not be ideal but it luckily coincided with decision to migrate my entire dev setup from Arch to NixOS. Thank you for your assistance and please let me know if I can be of assistance in your project.

**Comment by zaiste** [comment]
@marcociciriello There are some issues with properly managing background processes. I'm investigating how to do it properly and cleanly in Node.js.

Could you run the following command 

```
ps aux | grep postgresql
```

and provide a result here?

**Comment by zaiste** [comment]
I'm closing it as `stale`. Please let me know it the same error occurs in the newest version i.e. `0.69.0`.
